---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
      - name: {{ .Release.Name }}-master
        image: {{ .Values.container.image }}
        env:
         - name: REDIS_PASSWORD
           value: password123
        ports:
        - containerPort: 6379